config/routes.rb
Dataentry::Application.routes.draw do
  root :to => "welcome#home"
  resources :sampletypes
  resources :entrysamples
  resources :divers
  resources :habitattypes

end

app/models/diver.rb
class Diver < ActiveRecord::Base
  has_many :entry_sample



  #Validations
  validates_length_of :diver_name_id, :is => 4
  validates :diver_name_id, :uniqueness => true
  validates_format_of :diver_name_id, :with => /\d{4}/
  validates_format_of :diver_name, :with => /[A-Z]_[A-Z]/

end

app/models/entrysample.rb
class Entrysample < ActiveRecord::Base

  belongs_to :sample_type
  belongs_to :diver
  belongs_to :habitat_type  

  #Validations
  validates :sample_type_id, :presence => true
  validates :date, :presence => true
  validates :field_id, :presence => true, :uniqueness => true
  validates_format_of :field_id, :with => /\d\d\d\d[A-Z]/

  before_save :create_msn

  protected

  def create_msn
    self.mastersampcd = date.to_s(:number) + sample_start_time.to_formatted_s(:time).gsub(":", "") + diver_name_id
  end
end

app/models/habitattype.rb
class Habitattype < ActiveRecord::Base
  has_many :entry_sample

  #Validations
  validates :habitat_type_id, :presence => true
  validates :habitat_name, :presence => true
  validates :habitat_descr, :presence => true
end

app/models/sampletype.rb
class Sampletype < ActiveRecord::Base
  has_many :entry_sample
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/divers_controller.rb
class DiversController < ApplicationController
  def new
    @diver = Diver.new
    @divers = Diver.all
  end
  def create
    @diver = Diver.new(params[:diver])
    if @diver.save
      redirect_to new_diver_path
    else
      render :action => "new"
    end
  end

  def edit
    @diver = Diver.find(params[:id])
  end

  def update
    @diver = Diver.find(params[:id])
    if @diver.update_attributes(params[:diver])
      flash[:success] = "Diver updated"
      redirect_to new_diver_path
    else
      flash[:failure] = "Diver NOT updated"
      render :action => "new"
    end
  end
end

app/controllers/entrysamples_controller.rb
class EntrysamplesController < ApplicationController
  def new
    @entrysample = Entrysample.new
    @entrysamples = Entrysample.find(:all)
  end

  def create
    @entrysample = Entrysample.new(params[:entrysample])
    if @entrysample.save
      redirect_to new_entrysample_path
    else
      render :action => "new"
    end
  end      
end

app/controllers/habitattypes_controller.rb
class HabitattypesController < ApplicationController
  def new
    @habitattype = Habitattype.new
    @habitattypes = Habitattype.all
  end

  def create
    @habitattype = Habitattype.new(params[:habitattype])
    if @habitattype.save
      redirect_to new_habitattype_path
    else
      render :action => "new"
    end
  end

  def edit
    @habitattype = Habitattype.find(params[:id])
  end

  def update
    @habitattype = Habitattype.find(params[:id])
    if @habitattype.update_attributes(params[:habitattype])
      flash[:success] = "Habitat type updated"
      redirect_to new_habitattype_path
    else
      flash[:failure] = "Habitat type NOT updated"
      render :action => "new"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def new
  end

app/controllers/sampletypes_controller.rb
class SampletypesController < ApplicationController
  def new
    @sampletype = Sampletype.new
    @sampletypes = Sampletype.find(:all)
  end

  def create
    @sampletype = Sampletype.new(params[:sampletype])
    if @sampletype.save
      redirect_to new_sampletype_path
    end
  end

  def edit
    @sampletype = Sampletype.find(params[:id])
  end

  def update
    @sampletype = Sampletype.find(params[:id])
    if @sampletype.update_attributes(params[:sampletype])
      flash[:success] = "Sample type updated"
      redirect_to new_sampletype_path
    else
      flash[:failure] = "Sample type NOT updated"
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/divers_helper.rb
module DiversHelper
end

app/helpers/entrysamples_helper.rb
module EntrysamplesHelper
end

app/helpers/habitattypes_helper.rb
module HabitattypesHelper
end

app/helpers/sampletypes_helper.rb
module SampletypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/divers/_form.html.erb
Enter new Diver Information: <br />
<%= form_for @diver do |f| -%>
  <%= render 'shared/errormessages', :object => f.object %>
  diver_id: <%= f.text_field :diver_name_id %> <br />
  diver_name: <%= f.text_field :diver_name %> <br />
  <%= f.submit %>
<% end -%>

<hr />
List of all Divers: (click on name to edit)<br />
<% if !@divers.blank? %>
  <% for item in @divers %>
    <%= item.diver_name_id %>, <%= link_to item.diver_name, edit_diver_path(item) %><br />
  <% end %>
<% end %>

 <%= render 'shared/quick_links' %>

app/views/divers/edit.html.erb
<h1> Eidt a Diver </h1>
<%= render 'form' %>

app/views/divers/new.html.erb
<h1> Create new Diver </h1>

  <%= render 'form' %>

app/views/entrysamples/new.html.erb
Form for sample entry: <br />
<%= form_for @entrysample do |f| -%>
 <%= render 'shared/errormessages', :object => f.object %>

  DiverName: <%= f.collection_select(:diver_name_id, Diver.all, :diver_name_id, :diver_name, {:include_blank => ""}) %> <br />
  BuddyName: <%= f.collection_select(:buddy_name_id, Diver.all, :diver_name_id, :diver_name, {:include_blank => ""}) %> <br />
  SampleType: <%= f.collection_select(:sample_type_id, Sampletype.all, :id, :type_name, {:include_blank => ""})%> <br />
  HabitatType: <%= f.collection_select(:habitat_type_id, Habitattype.all, :habitat_type_id, :habitat_name, {:include_blank => ""})%> <br />
  date: <%= f.date_select :date, {:include_blank => "", :use_month_numbers => true, :order => [:month, :day, :year]} %> <br />
  FieldId: <%= f.text_field :field_id %><br />
  CylinderRadius(m): <%= f.select(:cylinder_radius, [7.5,5], {:include_blank => ""}) %> <br />
  Current: <%= f.select(:current, ["none", "mod.", "high"], {:include_blank => ""}) %><br />
  MaxDepth: <%= f.text_field :max_depth %><br />
  StationDepth: <%= f.text_field :station_depth %><br />
  UnderwaterVis: <%= f.text_field :vis %><br />
  WaterTemp: <%= f.text_field :water_temp %><br />
  DiveStartTime: <%= f.time_select :dive_start_time, {:include_blank => "", :ampm => true} %><br />
  DiveEndTime: <%= f.time_select :dive_end_time, {:include_blank => "", :ampm => true} %><br />
  SamppleStartTime: <%= f.time_select :sample_start_time, {:include_blank => "", :ampm => true} %><br />
  SampleEndTime: <%= f.time_select :sample_end_time, {:include_blank => "", :ampm => true} %><br />
  FishingGear: <%= f.text_field :fishgear %><br />
  Comments: <%= f.text_area :comments, :size => "60x12" %><br />
  <%= f.submit %>
<% end -%>
 <%= render 'shared/quick_links' %>

app/views/habitattypes/_form.html.erb
Enter new habitat type information:<br />
<%= form_for @habitattype do |f| -%>
  <%= render 'shared/errormessages', :object => f.object %>
    habitat_type_id: <%= f.text_field :habitat_type_id %> <br />
    habitat_name: <%= f.text_field :habitat_name %> <br />
    habitat_descr: <%= f.text_field :habitat_descr %> <br />
    <%= f.submit %>
  <% end -%>
  <hr />
List of all habitat types: (click on name to edit) <br />
<% if !@habitattypes.blank? %>
  <% for item in @habitattypes %> 
    <%= item.habitat_type_id %>, <%= link_to item.habitat_name, edit_habitattype_path(item)%>, <%= item.habitat_descr %> <br />
  <% end %>
<% else %>

<% end %>

 <%= render 'shared/quick_links' %>

app/views/habitattypes/edit.html.erb
<h1> Edit a habitat type </h1>
  <%= render 'form'%>

app/views/habitattypes/new.html.erb
<h1> Create new habitat type </h1>

  <%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dataentry</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sampletypes/_form.html.erb
Enter new sample type information: <br />
<%= form_for @sampletype do |f| -%>
    type_id: <%= f.text_field :type_id %> <br />
    type_name: <%= f.text_field :type_name %> <br />
    type_descr: <%= f.text_area :type_descr, :size => "30x3" %> <br />
    <%= f.submit %>
  <% end -%>
  <hr />
List of all sample types: (click on name to edit) <br />
<% if !@sampletypes.blank? %>
  <% for item in @sampletypes %> 
    <%= item.type_id %> <%= link_to item.type_name, edit_sampletype_path(item) %>, <%= item.type_descr %> <br />
  <% end %>
<% else %>

<% end %>

 <%= render 'shared/quick_links' %>

app/views/sampletypes/edit.html.erb
<h1> Edit a sample type </h1>

  <%= render 'form' %>

app/views/sampletypes/new.html.erb
<h1>Enter a new sample type</h1>

<%= render 'form'%>

app/views/shared/_errormessages.html.erb
<% if object.errors.any? %>
    <div class="error_explination">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/shared/_quick_links.html.erb
<hr />
  Quick Links: <%= link_to "Divers", new_diver_path %>, <%= link_to "Habitat Types", new_habitattype_path %>, <%= link_to "Sample Types", new_sampletype_path %>, <%= link_to "Entry Sample", new_entrysample_path %>

app/views/welcome/home.html.erb
<h1>RVC Data Entry Program</h1>

 <%= render 'shared/quick_links' %>